/* gen-fonts.js — regenerates finoptic/fonts.css from the .woff2 originals in
   fonts/.  Run from the project root (the folder holding CLAUDE.md):

     node scratchpad/gen-fonts.js --check    verify only, write nothing
     node scratchpad/gen-fonts.js            rewrite finoptic/fonts.css

   fonts.css has carried a "GENERATED FILE, do not hand-edit" header and a
   pointer to "the generator noted in status.md" since the fonts were first
   embedded — but no such script was ever committed, so this is it, written
   when Bricolage Grotesque was added for the Technomics wordmark.

   THE SAFETY GUARD, same shape as gen-monthly.js: before writing anything the
   script rebuilds the faces that are ALREADY in fonts.css and refuses to
   continue unless every one of their base64 payloads comes back byte-for-byte
   identical.  A file that is regenerated by a script written after the fact
   has to prove it reproduces what it is replacing; otherwise "regenerating"
   would quietly re-encode the brand type and nobody would know which bytes
   the browser had been rendering.

   Why base64 at all: the mock-up opens from file://, an opaque origin, and
   Chrome refuses cross-origin font files there even from the same folder.
   See the header this script emits. */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT  = path.join(ROOT, 'finoptic', 'fonts.css');
const SRC  = path.join(ROOT, 'fonts');
const CHECK = process.argv.includes('--check');

/* The two standard Google Fonts subset ranges.  Both were already in
   fonts.css and are shared by every face, so they live here once. */
const LATIN =
  'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,'+
  'U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,'+
  'U+FEFF,U+FFFD';
const LATIN_EXT =
  'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,'+
  'U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,'+
  'U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF';

/* One entry per @font-face, in the order they are emitted.  `weight` is the
   variable font's own wght axis range — narrowing it would make the browser
   synthesise weights the file can actually draw. */
const FACES = [
  {family:'Mona Sans',           weight:'200 900', file:'mona-sans-latin-wght-normal.woff2',                 range:LATIN,     note:'Mona Sans — latin'},
  {family:'Mona Sans',           weight:'200 900', file:'mona-sans-latin-ext-wght-normal.woff2',             range:LATIN_EXT, note:'Mona Sans — latin-ext'},
  {family:'Space Grotesk',       weight:'300 700', file:'space-grotesk-latin-wght-normal.woff2',             range:LATIN,     note:'Space Grotesk — latin'},
  {family:'Space Grotesk',       weight:'300 700', file:'space-grotesk-latin-ext-wght-normal.woff2',         range:LATIN_EXT, note:'Space Grotesk — latin-ext'},
  {family:'Bricolage Grotesque', weight:'200 800', file:'bricolage-grotesque-latin-wght-normal.woff2',       range:LATIN,     note:'Bricolage Grotesque — latin (the Technomics wordmark only)'},
  {family:'Bricolage Grotesque', weight:'200 800', file:'bricolage-grotesque-latin-ext-wght-normal.woff2',   range:LATIN_EXT, note:'Bricolage Grotesque — latin-ext'}
];

const HEADER = `/* =============================================================
   Technomics — webfont definitions.  GENERATED FILE, do not hand-edit.
   Regenerate with:  node scratchpad/gen-fonts.js

   Mona Sans + Space Grotesk (variable, weight axis only), from
   Fontsource: @fontsource-variable/mona-sans and /space-grotesk.
   Bricolage Grotesque (variable, weight axis only) joins them from
   @fontsource-variable/bricolage-grotesque — it sets the WORDMARK and
   nothing else, so it is not one of the product's two typefaces; there
   is no source artwork for the "Technomics" letterforms and this is the
   face the name was drawn in.  OFL-1.1, Atelier Triay.
   The .woff2 originals also sit in ../fonts/ next to this folder.

   Why base64 data: URIs instead of url(./fonts/x.woff2)?  This mock-up
   opens by double-click, so the page origin is file:// — an opaque
   origin, and Chrome refuses cross-origin font files there even from
   the same folder.  Data URIs are same-origin by definition, so the
   brand type renders in every browser, with or without a network.
   ============================================================= */
`;

function face(f){
  const b64 = fs.readFileSync(path.join(SRC, f.file)).toString('base64');
  return `
/* ${f.note} */
@font-face{
  font-family:'${f.family}';
  font-style:normal;
  font-weight:${f.weight};
  font-display:swap;
  src:url(data:font/woff2;base64,${b64}) format('woff2');
  unicode-range:${f.range};
}
`;
}

const missing = FACES.filter(f=>!fs.existsSync(path.join(SRC,f.file))).map(f=>f.file);
if(missing.length){ console.error('missing woff2:\n  '+missing.join('\n  ')); process.exit(1); }

/* --- the guard: every payload already in fonts.css must come back --- */
const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT,'utf8') : '';
const prevPayloads = [...prev.matchAll(/base64,([A-Za-z0-9+/=]+)\)/g)].map(m=>m[1]);
const nextPayloads = FACES.map(f=>fs.readFileSync(path.join(SRC,f.file)).toString('base64'));
const lost = prevPayloads.filter(p=>!nextPayloads.includes(p));
if(lost.length){
  console.error('REFUSING TO WRITE — '+lost.length+' payload(s) already in fonts.css do not\n'
    +'regenerate from ../fonts/.  The .woff2 originals and the stylesheet have\n'
    +'diverged; reconcile them by hand before running this again.');
  process.exit(1);
}

const out = HEADER + FACES.map(face).join('');
console.log('faces: '+FACES.length+'  (was '+prevPayloads.length+')');
FACES.forEach((f,i)=>console.log('  '+f.family.padEnd(21)+' '+f.range.slice(0,12).replace('U+0100','ext ')+'… '
  +(nextPayloads[i].length/1024).toFixed(0)+'KB b64'
  +(prevPayloads.includes(nextPayloads[i])?'  (unchanged)':'  NEW')));
console.log('guard: all '+prevPayloads.length+' existing payloads reproduce byte-for-byte');

if(CHECK){ console.log('\n--check: nothing written.  Output would be '+(out.length/1024).toFixed(0)+'KB.'); process.exit(0); }
fs.writeFileSync(OUT, out);
console.log('\nwrote '+path.relative(ROOT,OUT)+'  '+(out.length/1024).toFixed(0)+'KB');
