/* Round 14 — the Metrics tab and the insight band.

   The rule this file exists to hold: A KPI TILE MAY NOT RESTATE A LANE OF THE
   RECONCILIATION STRIP ON ITS OWN SCREEN.  That is checked on the RENDERED figures
   rather than on the source expressions, for the same reason table() sorts on
   rendered cells: the two come from different scopes through different formatters,
   and the printed string is the only thing a reader compares — which is exactly
   what the reviewer did.

   Also asserted here, because each was a decision rather than a side effect:
     - every tile carries a YTD byline, unless its figure is a structural count
     - a sparkline draws at least two points, or is absent entirely
     - the band is a LIST of at most two pointers per column
     - the six strip-duplicating screens carry no tab control at all
*/
const puppeteer = require('puppeteer-core');
const CHROME = 'C:/Users/lohit/.cache/puppeteer/chrome/win64-142.0.7444.175/chrome-win64/chrome.exe';
const U = 'file:///C:/Users/lohit/Desktop/crozaint/04-code/finoptic/finoptic/index.html';
const wait = ms => new Promise(r => setTimeout(r, ms));

const BOARD = ['overview','itfm','cloud','ai','saas','finance','proc','product','optimize',
               'allocation','forecast','anomalies','alerts','security','itsm'];
const DS = ['baseline','ai-crisis','optimised','scaleup','fresh','zero'];
/* The five that lost their Metrics tab: three of their four tiles were their own
   counterfoil, leaving one.  `optimize` is NOT among them — it looked like a
   four-tile screen in the source, but two of its tiles are generated by a .map()
   over the pipeline stages, so it still has three after the two colliding stages
   were dropped. */
const FLAT = ['allocation','forecast','anomalies','itsm','alerts'];

/* A figure is "the same" if the printed strings match once spacing is normalised.
   THE SIGN IS KEPT: `−$3K` is not `$3K`, and stripping it made a Variance of minus
   three thousand collide with a savings figure of plus three thousand on the two
   small datasets — a coincidence reported as a defect.
   An em dash matches nothing: an unmeasured workspace prints it everywhere and
   would otherwise report every tile on the board as a duplicate. */
const normFig = s => String(s||'').replace(/[\s,]/g,'').toLowerCase();
const normLbl = s => String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const DASHY = v => !v || /^[—–-]+$/.test(String(v).trim());

/* Words too common to make two labels the same subject.  Without this, "Security
   Cost Per Product" and "Cost Per Ticket" share "cost" and every per-unit metric
   on the board looks like every other one. */
const STOP = new Set(['the','and','of','per','in','to','a','not','yet','this','on','by',
                      'spend','cost','savings','saving','total','value','days','month',
                      'year','end','time','open','under','over','all']);
const words = s => String(s||'').toLowerCase().split(/[^a-z0-9]+/)
  .filter(w => w.length > 2 && !STOP.has(w));
/* Two labels name the same subject if they share a word that is not boilerplate.
   A matching FIGURE alone is a coincidence — two unrelated metrics can land on
   $3K.  A matching figure AND a shared subject is the defect. */
const sameSubject = (a,b) => { const B = new Set(words(b)); return words(a).some(w => B.has(w)); };

(async () => {
  const b = await puppeteer.launch({executablePath:CHROME, headless:true,
                                    args:['--allow-file-access-from-files']});
  const p = await b.newPage();
  await p.setViewport({width:1440, height:1000});
  const errs = [];
  p.on('pageerror', e => errs.push('pageerror: ' + e.message));
  p.on('console', m => { if(m.type()==='error') errs.push('console: ' + m.text()); });
  await p.goto(U + '?nofx', {waitUntil:'load'});
  await wait(700);

  const fails = [], warns = [];
  let renders = 0, tiles = 0, sparks = 0, bylines = 0;

  for(const d of DS){
    await p.evaluate(id => { loadScenario(id); refresh(); }, d);
    for(const s of BOARD){
      /* Both panes have to be readable, and the Metrics pane is display:none unless
         the switch is on it — so the switch goes on it, for every screen. */
      await p.evaluate(sc => { document.documentElement.setAttribute('data-sum','metrics'); go(sc); }, s);
      const r = await p.evaluate(() => {
        const txt = el => (el ? el.innerText.trim() : '');
        return {
          lanes: [...document.querySelectorAll('.ledger-cell')].map(c => ({
            k: txt(c.querySelector('.ledger-k')), v: txt(c.querySelector('.ledger-v'))
          })),
          tiles: [...document.querySelectorAll('.kpi')].map(t => ({
            k: txt(t.querySelector('.kpi-k')),
            v: txt(t.querySelector('.kpi-v')),
            ytd: txt(t.querySelector('.kpi-ytd')),
            spark: t.querySelectorAll('.kpi-spark svg').length,
            pts: t.querySelectorAll('.kpi-spark .ct-col').length,
            wait: t.classList.contains('kpi-wait')
          })),
          flat: !!document.querySelector('.sum-flat'),
          tabs: document.querySelectorAll('.sum-tab').length,
          more: document.querySelectorAll('.sum-more').length,
          cols: [...document.querySelectorAll('.briefing .brief')].map(c => ({
            lis: c.querySelectorAll('.brief-p > li').length,
            ps:  c.querySelectorAll(':scope > p').length
          }))
        };
      });
      renders++;
      const tag = `${d}/${s}`;

      /* ---- 1. the rule ---- */
      for(const t of r.tiles){
        tiles++;
        for(const L of r.lanes){
          /* An IDENTICAL LABEL is a repeat whatever the figures say — two lanes
             called "Budget" holding two different numbers is worse than two
             holding the same one, because the reader cannot tell which is which. */
          if(normLbl(t.k) && normLbl(t.k) === normLbl(L.k)){
            fails.push(`${tag}: tile "${t.k}" repeats strip label "${L.k}"`);
            continue;
          }
          if(DASHY(t.v) || DASHY(L.v) || normFig(t.v) !== normFig(L.v)) continue;
          if(sameSubject(t.k, L.k))
            fails.push(`${tag}: tile "${t.k}" (${t.v}) restates strip lane "${L.k}" (${L.v})`);
          else
            warns.push(`${tag}: tile "${t.k}" and lane "${L.k}" coincide at ${t.v} — unrelated metrics, same figure`);
        }
        /* ---- 2. bylines and sparklines ---- */
        if(t.ytd){
          bylines++;
          if(!/YTD$/.test(t.ytd)) fails.push(`${tag}: tile "${t.k}" byline does not end in YTD: "${t.ytd}"`);
        }
        if(t.spark){
          sparks++;
          if(t.spark > 1) fails.push(`${tag}: tile "${t.k}" has ${t.spark} sparklines`);
          if(t.pts < 2)   fails.push(`${tag}: tile "${t.k}" sparkline has ${t.pts} point(s) — draw none or draw a trend`);
          if(t.wait)      fails.push(`${tag}: tile "${t.k}" is waiting on data but drew a sparkline`);
        }
      }

      /* ---- 3. the band is a list of at most two ---- */
      for(const c of r.cols){
        if(c.ps)      fails.push(`${tag}: a band column still renders a <p> — pointers only`);
        if(c.lis > 2) fails.push(`${tag}: a band column has ${c.lis} pointers, max is 2`);
      }

      /* ---- 4. the tab control, where it should and should not be ---- */
      const shouldBeFlat = FLAT.includes(s);
      if(shouldBeFlat && r.tabs) fails.push(`${tag}: expected no tab control, found ${r.tabs} tabs`);
      if(shouldBeFlat && r.more) fails.push(`${tag}: flat screen still offers "View KPIs"`);
      if(!shouldBeFlat && r.tiles.length > 1 && !r.tabs)
        fails.push(`${tag}: expected a tab control, found none`);
    }
  }

  console.log(`${renders} renders · ${tiles} tiles · ${sparks} sparklines · ${bylines} YTD bylines`);
  if(errs.length){ console.log('\nJS errors:'); errs.slice(0,10).forEach(e => console.log('  ' + e)); }
  if(fails.length){
    console.log(`\n${fails.length} failure(s):`);
    /* Deduplicated: one broken tile otherwise reports six times, once per dataset,
       and the list stops being readable at exactly the moment it matters. */
    const seen = new Set();
    for(const f of fails){
      const key = f.replace(/^[a-z-]+\//,'');
      if(seen.has(key)) continue;
      seen.add(key);
      console.log('  ' + f);
    }
    console.log(`  (${fails.length} total, ${seen.size} distinct)`);
  }else{
    console.log('\nNo tile restates a strip lane. Bylines, sparklines, pointers and tabs all correct.');
  }
  /* Reported, never failed.  A coincidence on a small dataset is worth seeing —
     if one turns out to be two names for one number, it becomes a failure by
     acquiring a shared word, which is the point of the distinction. */
  if(warns.length){
    const seen = new Set();
    const lines = warns.filter(w => { const k = w.replace(/^[a-z-]+\//,''); return seen.has(k) ? false : seen.add(k); });
    console.log(`\n${lines.length} coincidence(s), not failures:`);
    lines.forEach(w => console.log('  ' + w));
  }
  await b.close();
  process.exit(fails.length || errs.length ? 1 : 0);
})();
